export const CENTER_LIST='CENTER_LIST'
export const CENTER_DETAIL='CENTER_DETAIL'

export const HEALTH_LIST='HEALTH_LIST'
export const HEALTH_DETAIL='HEALTH_DETAIL'

export const FETCH_BOARD_LIST='FETCH_BOARD_LIST'
export const FETCH_BOARD_DETAIL='FETCH_BOARD_DETAIL'
export const FETCH_BOARD_INSERT='FETCH_BOARD_INSERT'
export const FETCH_BOARD_UPDATE='FETCH_BOARD_UPDATE'
export const BOARD_UPDATE_OK='BOARD_UPDATE_OK'
export const FETCH_BOARD_DELETE='FETCH_BOARD_DELETE'

export const HEALTH_MAIN='HEALTH_MAIN'
